services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "1883:1883"
      - "8883:8883"
      - "5672:5672" # RabbitMQ AMQP
    environment:
      RABBITMQ_HOST: '%'
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: root
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
    configs:
      - source: plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - type: bind
        source: ./rmq/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
        read_only: true
      - type: bind
        source: ./rmq/definitions.json
        target: /etc/rabbitmq/definitions.json
        read_only: true
        # certs
      - type: bind
        source: ./crt/iot_leo4_ca.crt
        target: /crt/ca_certificate.pem
        read_only: true
      - type: bind
        source: ./crt/cert_0000.pem
        target: /crt/server_certificate.pem
        read_only: true
      - type: bind
        source: ./crt/key_0000.pem
        target: /crt/server_key.pem
        read_only: true
#ssl_options.cacertfile = /crt/ca_certificate.pem
#ssl_options.certfile   = /crt/server_certificate.pem
#ssl_options.keyfile    = /crt/server_key.pem
      #- ./rmq/rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics", "-q", "ping" ]
      retries: 3
      timeout: 5s
      interval: 30s
configs:
  plugins:
    content: "[rabbitmq_management, rabbitmq_mqtt]." 
volumes:
  rabbitmq_data:
    driver: local

networks:
  rabbitmq_network:
    driver: bridge
