"""add devicegauge

Revision ID: 4ac4bc5f8f0e
Revises: 10c52a60cbe2
Create Date: 2025-10-25 10:54:05.855828

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4ac4bc5f8f0e"
down_revision: Union[str, Sequence[str], None] = "10c52a60cbe2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_device_gauges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP(0)"),
            nullable=False,
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("gauges", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["tb_devices.device_id"],
            name=op.f("fk_tb_device_gauges_device_id_tb_devices"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tb_device_gauges")),
        sa.UniqueConstraint(
            "device_id",
            "type",
            "is_deleted",
            name=op.f("uq_tb_device_gauges_device_id_type_is_deleted"),
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("tb_device_gauges")
    # ### end Alembic commands ###
