"""add deleted in device_tasks, device

Revision ID: 26ba52b91608
Revises: ec809f7d6f20
Create Date: 2025-08-24 13:55:19.122574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26ba52b91608"
down_revision: Union[str, Sequence[str], None] = "ec809f7d6f20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tb_dev_tasks", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "tb_dev_tasks", sa.Column("deleted_at", sa.Integer(), nullable=False)
    )
    op.add_column(
        "tb_devices", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "tb_devices", sa.Column("deleted_at", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_devices", "deleted_at")
    op.drop_column("tb_devices", "is_deleted")
    op.drop_column("tb_dev_tasks", "deleted_at")
    op.drop_column("tb_dev_tasks", "is_deleted")
    # ### end Alembic commands ###
