"""add field DevTaskResult

Revision ID: d4aead72d80f
Revises: ca67ea23e0fd
Create Date: 2025-09-14 14:46:10.790630

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4aead72d80f"
down_revision: Union[str, Sequence[str], None] = "ca67ea23e0fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tb_dev_task_results",
        sa.Column("ext_id", sa.Integer(), nullable=False),
    )
    op.add_column(
        "tb_dev_task_results",
        sa.Column("status_code", sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_dev_task_results", "status_code")
    op.drop_column("tb_dev_task_results", "ext_id")
    # ### end Alembic commands ###
