"""add fields DeviceConnection

Revision ID: 27e956d5557d
Revises: 9b9e7b582a61
Create Date: 2025-09-20 16:04:41.598314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "27e956d5557d"
down_revision: Union[str, Sequence[str], None] = "9b9e7b582a61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tb_device_connections",
        sa.Column("client_id", sa.String(), nullable=True),
    )
    op.add_column(
        "tb_device_connections",
        sa.Column("last_checked_result", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "tb_device_connections",
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_device_connections", "details")
    op.drop_column("tb_device_connections", "last_checked_result")
    op.drop_column("tb_device_connections", "client_id")
    # ### end Alembic commands ###
