"""fix deleted_at default in device_tasks, device

Revision ID: d5bbefccd315
Revises: 26ba52b91608
Create Date: 2025-08-24 14:19:42.164561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5bbefccd315"
down_revision: Union[str, Sequence[str], None] = "26ba52b91608"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
