"""add Org, DeviceOrgBind

Revision ID: 9b9e7b582a61
Revises: d4aead72d80f
Create Date: 2025-09-16 00:46:44.550188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9b9e7b582a61"
down_revision: Union[str, Sequence[str], None] = "d4aead72d80f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_orgs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tb_orgs")),
        sa.UniqueConstraint("org_id", name=op.f("uq_tb_orgs_org_id")),
    )
    op.create_table(
        "tb_device_org_binds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["tb_devices.device_id"],
            name=op.f("fk_tb_device_org_binds_device_id_tb_devices"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["tb_orgs.org_id"],
            name=op.f("fk_tb_device_org_binds_org_id_tb_orgs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tb_device_org_binds")),
        sa.UniqueConstraint("device_id", name=op.f("uq_tb_device_org_binds_device_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tb_device_org_binds")
    op.drop_table("tb_orgs")
    # ### end Alembic commands ###
