"""add dev event

Revision ID: 9e643fa8a7d8
Revises: 01aa777e1e85
Create Date: 2025-09-01 15:26:34.769634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e643fa8a7d8"
down_revision: Union[str, Sequence[str], None] = "01aa777e1e85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_dev_tasks", sa.Column("ext_task_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_dev_tasks", "ext_task_id")
    # ### end Alembic commands ###
