"""add dev event

Revision ID: ddffc971adc2
Revises: 9e643fa8a7d8
Create Date: 2025-09-01 15:31:30.704986

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ddffc971adc2"
down_revision: Union[str, Sequence[str], None] = "9e643fa8a7d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_dev_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("event_type_code", sa.Integer(), nullable=False),
        sa.Column("dev_event_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True, precision=0),
            server_default=sa.text("CURRENT_TIMESTAMP(0)"),
            nullable=True,
        ),
        sa.Column(
            "dev_timestamp", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "payload", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tb_dev_events")),
    )
    op.create_index(
        op.f("ix_tb_dev_events_dev_event_id"),
        "tb_dev_events",
        ["dev_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tb_dev_events_device_id"),
        "tb_dev_events",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tb_dev_events_event_type_code"),
        "tb_dev_events",
        ["event_type_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tb_dev_events_event_type_code"), table_name="tb_dev_events"
    )
    op.drop_index(
        op.f("ix_tb_dev_events_device_id"), table_name="tb_dev_events"
    )
    op.drop_index(
        op.f("ix_tb_dev_events_dev_event_id"), table_name="tb_dev_events"
    )
    op.drop_table("tb_dev_events")
    # ### end Alembic commands ###
