"""add dev sn uniq

Revision ID: ca67ea23e0fd
Revises: ddffc971adc2
Create Date: 2025-09-02 18:21:50.054070

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca67ea23e0fd"
down_revision: Union[str, Sequence[str], None] = "ddffc971adc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tb_devices", "sn", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_unique_constraint(op.f("uq_tb_devices_sn"), "tb_devices", ["sn"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_tb_devices_sn"), "tb_devices", type_="unique")
    op.alter_column(
        "tb_devices", "sn", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
